version: '3'
services:
  travis-shield:
    image: richiesams/travis_shield
    container_name: travis-shield
    environment:
      - VIRTUAL_HOST=shield.adrianastley.com
      - LETSENCRYPT_HOST=shield.adrianastley.com
      - LETSENCRYPT_EMAIL=adastley@gmail.com
    restart: always

networks:
  default:
    external:
      name: webproxy
