version: '3'
services:
  nginx-website:
    image: nginx:1.13.3-alpine
    container_name: nginx-website
    environment:
      - VIRTUAL_HOST=adrianastley.com
      - LETSENCRYPT_HOST=adrianastley.com
      - LETSENCRYPT_EMAIL=adastley@gmail.com
    volumes:
      - /dockervols/site-html:/usr/share/nginx/html:ro
      - ./site/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /dockervols/nginx-cache:/var/run/nginx-cache
    restart: always

networks:
  default:
    external:
      name: webproxy
