version: '3'
services:
  nginx:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /dockervols/proxy/conf.d:/etc/nginx/conf.d
      - /dockervols/proxy/vhost.d:/etc/nginx/vhost.d
      #- /dockervols/proxy/html:/usr/share/nginx/html
      - /dockervols/proxy/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - /dockervols/proxy/conf.d:/etc/nginx/conf.d
      - /dockervols/proxy/vhost.d:/etc/nginx/vhost.d
      #- /dockervols/proxy/html:/usr/share/nginx/html
      - /dockervols/proxy/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - /dockervols/proxy/conf.d:/etc/nginx/conf.d
      - /dockervols/proxy/vhost.d:/etc/nginx/vhost.d
      #- /dockervols/proxy/html:/usr/share/nginx/html
      - /dockervols/proxy/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"
      
  rancher-server:
    image: rancher/server:stable
    environment:
      - VIRTUAL_HOST=rancher.adrianastley.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=rancher.adrianastley.com
      - LETSENCRYPT_EMAIL=adastley@gmail.com
    volumes:
      - /dockervols/rancher:/var/lib/mysql
    expose:
      - "8080"
    restart: unless-stopped
