version: '3'
services:
  travis-shield:
    image: nginx:1.13.3-alpine
    container_name: travis-shield
    environment:
      - VIRTUAL_HOST=shield.adrianastley.com
      - LETSENCRYPT_HOST=shield.adrianastley.com
      - LETSENCRYPT_EMAIL=adastley@gmail.com
    volumes:
      - /dockervols/site-html:/usr/share/nginx/html:ro
      - ./site/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always

networks:
  default:
    external:
      name: webproxy
