version: '3'
services:
  nginx-ssl-proxy:
    image: nginx:1.13.3-alpine
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx-ssl-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /dockervols/proxy/conf.d:/etc/nginx/conf.d
      - /dockervols/proxy/vhost.d:/etc/nginx/vhost.d
      - /dockervols/proxy/html:/usr/share/nginx/html
      - /dockervols/proxy/certs:/etc/nginx/certs:ro
      - /dockervols/proxy/htpasswd:/etc/nginx/htpasswd:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-ssl-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: always
    volumes:
      - /dockervols/proxy/conf.d:/etc/nginx/conf.d
      - /dockervols/proxy/vhost.d:/etc/nginx/vhost.d
      - /dockervols/proxy/html:/usr/share/nginx/html
      - /dockervols/proxy/certs:/etc/nginx/certs:ro
      - /dockervols/proxy/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    environment:
      - RESOLVERS=8.8.8.8

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    volumes:
      - /dockervols/proxy/conf.d:/etc/nginx/conf.d
      - /dockervols/proxy/vhost.d:/etc/nginx/vhost.d
      - /dockervols/proxy/html:/usr/share/nginx/html
      - /dockervols/proxy/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx-ssl-proxy"

networks:
  default:
    external:
      name: webproxy
